global using System;
global using System.Runtime.InteropServices;
global using FFXIVClientStructs.Interop;
global using FFXIVClientStructs.Interop.Attributes;
global using static HaselTweaks.Utils.Globals.Addon;
global using static HaselTweaks.Utils.Globals.Agent;
global using static HaselTweaks.Utils.Globals.Atk;
global using static HaselTweaks.Utils.Globals.Excel;
global using static HaselTweaks.Utils.Globals.Strings;
global using static HaselTweaks.Utils.Globals.Tweaks;
