global using System;
global using System.Runtime.InteropServices;
global using InteropGenerator.Runtime;
global using InteropGenerator.Runtime.Attributes;
global using static FFXIVClientStructs.Interop.SpanExtensions;
global using static HaselCommon.Utils.Globals.Addon;
global using static HaselCommon.Utils.Globals.Agent;
global using static HaselCommon.Utils.Globals.Atk;
global using static HaselCommon.Utils.Globals.Excel;
global using static HaselCommon.Utils.Globals.Statics;
global using static HaselCommon.Utils.Globals.Strings;
global using Service = HaselCommon.Service;
