name: Build Plugin

env:
  plugin_name: HaselTweaks

on:
  push:
    paths-ignore:
      - .editorconfig
      - .gitattributes
      - .github/**
      - .gitignore
      - HaselTweaks/Translations.json
      - CHANGELOG.md
      - LICENSE
      - README.md
  workflow_dispatch:
    inputs:
      dalamud_branch:
        description: 'Dalamud Branch'
        required: true
        default: 'master'
        type: choice
        options:
          - master
          - stg

jobs:
  build:
    name: Build
    runs-on: windows-latest
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
      is_release: ${{ startsWith(github.ref, 'refs/tags/v') && github.event_name != 'pull_request' }}

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          cache: true
          cache-dependency-path: ${{ env.plugin_name }}/packages.lock.json
          global-json-file: global.json

      - name: Cache Native Build
        id: cache-native
        uses: actions/cache@v6
        with:
          path: |
            bin/HaselTweaks.Native.dll
            bin/HaselTweaks.Native.pdb
          key: native-build-${{ runner.os }}-${{ hashFiles('HaselTweaks.Native/**') }}

      - name: Install Native Build Tools
        if: steps.cache-native.outputs.cache-hit != 'true'
        run: |
          choco install nasm xmake -y
          Add-Content -Path $env:GITHUB_PATH -Value "C:\Program Files\xmake"

      - name: Build cpp project
        if: steps.cache-native.outputs.cache-hit != 'true'
        working-directory: HaselTweaks.Native
        shell: cmd
        run: build.bat

      - name: Download Dalamud
        shell: bash
        env:
          DALAMUD_URL: |-
            ${{ case(
              github.event.inputs.dalamud_branch == 'stg' || github.event.ref == 'refs/heads/stg' || startsWith(github.event.head_commit.message, '[stg]'), 'https://goatcorp.github.io/dalamud-distrib/stg/latest.zip',
              'https://goatcorp.github.io/dalamud-distrib/latest.zip'
            ) }}
        run: |
          curl -o latest.zip ${{ env.DALAMUD_URL }}
          mkdir -p ~/AppData/Roaming/XIVLauncher/addon/Hooks/dev
          unzip latest.zip -d ~/AppData/Roaming/XIVLauncher/addon/Hooks/dev/

      - name: Build csharp project
        run: |
          dotnet restore --locked-mode
          dotnet build --no-restore -c Release -clp:NoSummary

      - name: Rename manifest
        if: github.event_name != 'pull_request'
        shell: bash
        run: mv bin/${{ env.plugin_name }}/${{ env.plugin_name }}.json bin/${{ env.plugin_name }}/manifest.json

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v7
        with:
          path: bin/${{ env.plugin_name }}/*

      - name: Extract release notes
        if: success() && env.is_release == 'true'
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v3

      - name: Release
        if: success() && env.is_release == 'true'
        uses: softprops/action-gh-release@v3
        with:
          name: ${{ env.plugin_name }} ${{ github.ref_name }}
          body: ${{ steps.extract-release-notes.outputs.release_notes }}
          files: bin/${{ env.plugin_name }}/*

      - name: Trigger Repo Update
        if: success() && env.is_release == 'true'
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.repository_owner }}/MyDalamudPlugins
          event-type: new-release
